language: ruby

sudo: required
dist: trusty

env:
  global:
    - JOSE_CRYPTO_FALLBACK=true
    - RUBYOPT="-W0"

rvm:
  - 2.5.1

notifications:
  email: false

before_install:
  - "gem install bundler -v 1.16.4"
