language: ruby

sudo: required
dist: trusty

env:
  global:
    - JOSE_CRYPTO_FALLBACK=true
    - RUBYOPT="-W0"

rvm:
  - 2.7.0

notifications:
  email: false

before_install:
  - "gem install bundler -v 2.1.4"
