language: ruby

sudo: required
dist: bionic

env:
  global:
    - COVERAGE=true
    - JOSE_CRYPTO_FALLBACK=true
    - RUBYOPT="-W0"

rvm:
  - 2.7.1

notifications:
  email: false

before_install:
  - "gem install bundler -v 2.1.4"
