name: CI

on: [push, pull_request]

env:
  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  COVERAGE: true
  JOSE_CRYPTO_FALLBACK: true
  RUBYOPT: "-W0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7.8', '3.2.2', '3.3.0']

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
